version: '3.7'

services:
  app:
    build:
      context: .
      target: builder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 4
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000

